platform :ios, '7.0'

inhibit_all_warnings!

target 'DSBaseViewController-Example' do
    pod 'DSBaseViewController', :path => '../'
    pod 'CocoaLumberjack'

#    post_install do |installer|
#        installer.pods_project.targets.each do |target|
#            target.build_configurations.each do |config|
#                # Inject the final super class as base.
#                if target.name == 'DSBaseViewController'
#                    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
##                    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'BASEVIEWCONTROLLER=HardBasedViewController'
#                end
#            end
#        end
#    end
end
